# Generated by Django 4.0.3 on 2022-04-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0002_movie_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviefavorites',
            name='rating',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3, max_length=1),
        ),
    ]
