# Generated by Django 4.0.3 on 2022-03-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieWeb', '0003_film_description_film_imdb_rating_film_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.PositiveSmallIntegerField(choices=[(3, 'Sci-Fi'), (2, 'Comedy'), (0, 'Other'), (1, 'Horror'), (4, 'Drama')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='additional',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MovieWeb.additionalinfo'),
        ),
    ]
